export class GenerateResponseDto {
  /**
   * Ordered list of actionable Arabic task strings generated by the AI.
   * Always contains exactly 4 items (generated by task_prompt.py).
   * Falls back to 3 general tasks if the AI pipeline fails.
   */
  tasks!: string[];

  /**
   * Indicates whether tasks came from the live AI pipeline or the
   * built-in fallback. Useful for observability and analytics.
   *  - 'llm'      → tasks generated by SambaNova via FastAPI ai-logic
   *  - 'fallback' → AI failed; safe default tasks returned instead
   */
  source!: 'llm' | 'fallback';

  /**
   * The clean extracted goal in Arabic.
   * Example: input "عايز أتعلم برمجة" → main_goal: "تعلم البرمجة"
   * Extracted by goal_prompt.py inside the FastAPI service.
   */
  main_goal?: string;

  /**
   * A friendly Arabic confirmation message to show the user.
   * Example: "هيبقى عندك خطة ممتازة لتعلم البرمجة 💪"
   * Generated by goal_prompt.py inside the FastAPI service.
   */
  response_ar?: string;
}